// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAncZPtOYNrgpFAgct_JM-tqc3i032GoXQ',
    appId: '1:385234243606:web:1dd0fb82cadb2f08cb6537',
    messagingSenderId: '385234243606',
    projectId: 'hr-system-e8fba',
    authDomain: 'hr-system-e8fba.firebaseapp.com',
    storageBucket: 'hr-system-e8fba.firebasestorage.app',
    measurementId: 'G-Z6Z14WFRXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6h8ClbBFY09CDnnIpsYZNrn1e65g-OB8',
    appId: '1:385234243606:android:faf6f102e183bed6cb6537',
    messagingSenderId: '385234243606',
    projectId: 'hr-system-e8fba',
    storageBucket: 'hr-system-e8fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eBKq9C3RGANxdeINE1-Le0oZKT9KJAU',
    appId: '1:385234243606:ios:e640c4b4d3cf27accb6537',
    messagingSenderId: '385234243606',
    projectId: 'hr-system-e8fba',
    storageBucket: 'hr-system-e8fba.firebasestorage.app',
    iosBundleId: 'com.example.hrDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7eBKq9C3RGANxdeINE1-Le0oZKT9KJAU',
    appId: '1:385234243606:ios:e640c4b4d3cf27accb6537',
    messagingSenderId: '385234243606',
    projectId: 'hr-system-e8fba',
    storageBucket: 'hr-system-e8fba.firebasestorage.app',
    iosBundleId: 'com.example.hrDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAncZPtOYNrgpFAgct_JM-tqc3i032GoXQ',
    appId: '1:385234243606:web:a95da70df4fdbf86cb6537',
    messagingSenderId: '385234243606',
    projectId: 'hr-system-e8fba',
    authDomain: 'hr-system-e8fba.firebaseapp.com',
    storageBucket: 'hr-system-e8fba.firebasestorage.app',
    measurementId: 'G-TFQBXDNJHV',
  );
}
